# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 924f8b041a4226a6b112343b1846352b246137fdb8780a2a7506d7e62c779a6ea22c358c54ce905b373a036d1391f5387a80f04dddab939148f1275ebfd3be8e

test:
  secret_key_base: 00c66796102e87a58462e539d09a5a73bbb5763156597ac48facabb2108d689ab1a2e716eef7f543f78df2307f17457ae20d1b29bc1451fbee8137b1bb4d0b31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
